### ISSUE TITLE
Uploading results guidance appears to have parameters order switched

### ISSUE THREAD

**Issue by johnmahoneyASC** [projectcypress/cypress-dotnet-sdk#1]
var task = client.ProductTestsProductTestIdTasks.GetById(productTestID, taskID).Result.Content;

should be 
 var task = client.ProductTestsProductTestIdTasks.GetById(taskID, productTestID).Result.Content;

??

**Comment by ssayer** [comment]
the first line makes more sense, since tasks are nested under product tests. If this is happening in the wrong order in the API, we'll take a look and see what's going on. We should be able to look into this sometime next week

**Comment by dehall** [comment]
@johnmahoneyASC you are correct - the right order of parameters is client.ProductTestsProductTestIdTasks.GetById(taskID, productTestID) . The code generator we're using puts the parameters in a different order than we usually expect so it's easy to get tripped up. I'll update the documentation
